### ISSUE TITLE
SVG - sibling element becomes subelement

### ISSUE THREAD

**Issue by BKFlister** [thomasborgen/hypermedia#48] opened 2024-11-07 06:46 UTC
I am struggling getting this simple svg correct with hypermedia.

Original svg
```html
<svg width="18px" height="18px" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
    stroke-linecap="round" stroke-linejoin="round">
    <line x1="5" y1="19" x2="5" y2="5"></line>
    <polygon points="19 20 9 12 19 4 19 20"></polygon>
</svg>
```

Hypermedia python code:
```python
Svg(
    Line(x1='5', y1='19', x2='5', y2='5'),
    Polygon(points='19 20 9 12 19 4 19 20'),
    width='18px', height='18px', viewbox='0 0 24 24', fill='none',
    stroke='currentColor', stroke_width='2', stroke_linecap='round', stroke_linejoin='round'
)
```

Generated svg:
```html
<svg width="18px" height="18px" viewBox="0 0 24 24" fill="none" stroke="currentColor" 
    stroke-width="2" stroke-linecap="round" stroke-linejoin="round" href="#">
    <line x1="19" y1="5" x2="19" y2="19">
        <polygon points="5 4 15 12 5 20 5 4"></polygon>
    </line>
</svg>
```
`polygon` becomes a sub-element of `line`.

What is the correct syntax to create the svg?

**Comment by thomasborgen** [comment] 2024-11-07 11:12
Hi @BKFlister 
Thanks again for finding a bug. 

This is caused by svg being XML and needing properly closed tag endings: `/>` whereas normal html void elements like `<br>` and `<link>` in the header does not need the `/` to be closed properly. 

So there are two options.

1. Make a XMLVoidElement for the svg elements to inherit from that will close out the tags with `/>` whenever.
2. Always use `/>` for everything.

Generally i want to just stick to the spec with HTML which says that `/>` is not needed. 
Because of that I'm leaning towards having a xml void element that these few svg elements can inherit from. In the end, these are details that anyone using hypermedia will not be exposed to and should not have to care about.

I'll get on it as soon as I can unless you want to have a go at it.

**Comment by thomasborgen** [comment] 2024-11-08 09:06
Please test with version 5.3.3 and close the issue if it is solved :)

**Closed** 2024-11-08 16:42 UTC
Labels: bug, semver[patch]
